apiVersion: v1
kind: Namespace
metadata:
  name: api3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-serviceaccount
  namespace: api3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: api3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api3
  template:
    metadata:
      labels:
        app: api3
    spec:
      serviceAccount: api-serviceaccount
      containers:
      - name: app
        image: api-test:local
        imagePullPolicy: Never
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: LISTEN_ADDR
          value: ":8080"
        - name: STORAGE_HUB_SVC
          value: "http://app.storage-hub.svc.cluster.local"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: api3
spec:
  type: NodePort
  selector:
    app: api3
  ports:
    - port: 8080
      targetPort: 8080
