apiVersion: v1
kind: Namespace
metadata:
  name: storage-hub
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-hub
  namespace: storage-hub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-reader
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings", "roles"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-reader
subjects:
  - kind: ServiceAccount
    name: storage-hub
    namespace: storage-hub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rolebinding-read-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: storage-hub
    namespace: storage-hub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-hub
  namespace: storage-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-hub
  template:
    metadata:
      labels:
        app: storage-hub
    spec:
      serviceAccount: storage-hub
      containers:
        - name: app
          image: storage-hub:local
          imagePullPolicy: Never
          env:
            - name: LISTEN_ADDR
              value: ":8081"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: storage-hub
spec:
  selector:
    app: storage-hub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
